### ISSUE TITLE
co_ti_cmb_metadata missing from data portal

### ISSUE THREAD

**Issue by anisdismail** [LJ-Kong/cd_atlas_single_cell#1]
I am trying to reproduce the results of the paper and I could not find the co_ti_cmb_metadata file over the data portal. The only metadata file I found there: scp_metadata_combined.v2.txt do not contain the same conditions for the patients as reported in the paper: heatlhy, non-inflamed and inflamed. Is it possible to know how to obtain those conditions to be able to reproduce the results exactly?

**Comment by LJ-Kong** [comment]
Hello, sorry for the confusion. The co_ti_cmb_metadata.zip file is in the repository where this issue is filed. Specifically, at: https://github.com/LJ-Kong/cd_atlas_single_cell/tree/main/data

**Comment by anisdismail** [comment]
thank you for your support!
